### PR TITLE
czech translations

### PR DESCRIPTION
**Pull request by mastnym**
Simply translations to Czech language, great plugin, thanks

### CODE REVIEW

**Comment by ndunand** [comment]
Thanks a lot! But could you use lang.moodle.org (AMOS) to set these strings? That's the supported way of doing it. See this for more information: https://docs.moodle.org/dev/Translating_plugins#Looking_for_translated_plugins_in_the_Moodle_plugins_database .

French files are here for historical reasons, and I should also remove then.

**Comment by ndunand** [comment]
Here, I just moved the FR translation out to AMOS, cf. 376423a

**Comment by mastnym** [comment]
Great, I did the same with Czech translations. 
Closing pull request now

**Comment by ndunand** [comment]
Fantastic, thanks!

**Pull request closed without merging**
